empower_her_rise/DHO/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns=[
   path('addschema',views.addschema),
   path('viewschema',views.viewschema),
    path('deleteschema/<int:id>',views.deleteschema),
   path('editschema/<int:id>',views.editschema),

   path('addcheckup',views.addcheckup),
   path('viewcheckup',views.viewcheckup),
    path('deletecheckup/<int:id>',views.deletecheckup),
   path('editcheckup/<int:id>',views.editcheckup),
   path('view_more_schema/<int:id>',views.view_more_schema),


]

empower_her_rise/authentication/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
   path('',views.index),
   path('user',views.register),
   path('Home',views.Home),
   path('org',views.OrgRegister),
   path('dhoreg',views.DHOregister),
   path('policeofficer',views.policeofficerRegister),
   path('login',views.doLogin),
      path('bookclass/<int:id>',views.bookclass),
 



   path('about',views.About),
   path('logout',views.dologout)

]

empower_her_rise/empower_her_rise/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('',include('Admin_App.urls')),
    path('',include('DHO.urls')),
    path('',include('organization.urls')),
    path('',include('Police.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empower_her_rise/Admin_App/models.py
from django.db import models
from authentication.models import *
from django.utils import timezone
from authentication.models import *
from .models import *

classt=[
    ('','Select'),
    ('online','online'),
    ('offline','offline')
]

# Create your models here.
class Talentgroup(models.Model):
    title = models.CharField(max_length=50,default='')
    description = models.TextField(default='')


class classes(models.Model):
    userid = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='gftftyfftyfuoiop')
    title = models.CharField(max_length=50,default='')
    description = models.TextField(max_length=50,default='')
    start_time=models.TimeField(null=True)
    end_time=models.TimeField(null=True)
    date=models.DateField(null=True)
    amount=models.IntegerField(null=True)
    place = models.CharField(max_length=50,default='')
    class_type= models.CharField(max_length=50,default='',choices=classt)


class inbox(models.Model):
    sender = models.ForeignKey(Register, related_name='service_person', on_delete=models.CASCADE, null=True)
    reciever = models.ForeignKey(Register, related_name='org_id', on_delete=models.CASCADE, null=True)
    message = models.TextField(null=True)
    datetime=models.DateTimeField(null=True)
    status = models.IntegerField(null=True, default=0)


class members(models.Model):
    userid = models.ForeignKey(Register, related_name='service_WDEWQperson', on_delete=models.CASCADE, null=True)
    gpid = models.ForeignKey(Talentgroup, related_name='orgWEWRE_id', on_delete=models.CASCADE, null=True)
    status = models.IntegerField(null=True, default=0)

       
class classvideo(models.Model):
    classid = models.ForeignKey(classes, related_name='ertewrtwert', on_delete=models.CASCADE, null=True)
    video = models.FileField(null=True)


class booking(models.Model):
    user = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='sdassigfhjkadgtsdgghjd')
    classid = models.ForeignKey(classes,on_delete=models.CASCADE,null=True,related_name='adssigfetwrtewrthjkghjd')
    status=models.IntegerField(null=True,default=0)

class feedback(models.Model):
    userid = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='sdassigfhdfhydfhetjkadgtsdgghjd')
    classid = models.ForeignKey(classes,on_delete=models.CASCADE,null=True,related_name='adssigfetwtetrterrtewrthjkghjd')
    feedback =models.TextField(null=True)
    reply=models.TextField(null=True)
    status=models.IntegerField(null=True,default=0)


class groupinbox(models.Model):
    sender = models.ForeignKey(Register, related_name='sdr', on_delete=models.CASCADE, null=True)
    groupid = models.ForeignKey(Talentgroup, related_name='sdererr', on_delete=models.CASCADE, null=True)

    message = models.TextField(null=True)
    datetime=models.DateTimeField(null=True)

empower_her_rise/DHO/models.py
from django.db import models
from authentication.models import*
# Create your models here.
class healthcheckup(models.Model):
    userid = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='osfsdiop')
    title = models.CharField(max_length=50,default='')
    description = models.TextField(default='')
    place = models.CharField(max_length=50,default='')
    date = models.DateField(null=True)
    time = models.TimeField(null=True)

class Schemas(models.Model):
    userid = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='osdfsdiop')
    title = models.CharField(max_length=50,default='')
    link = models.CharField(max_length=250,default='')

    description = models.TextField(default='')
    required = models.TextField(default='')

empower_her_rise/Police/models.py
from django.db import models

# Create your models here.
class selfdefenceclasses(models.Model):
    title = models.CharField(max_length=50,default='')
    description = models.CharField(max_length=50,default='')
    place = models.CharField(max_length=50,default='')
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    class_type=models.CharField(max_length=50,default='')

empower_her_rise/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
state=[
    ('','Select'),
    ('Kerala','Kerala')
]


district=[
    ('','Select'),
    ('Thrissur','Thrissur')
]


gender=[
    ('','Select'),
    ('Male','Male'),
    ('Female','Female'),
    ('Other','Other'),

]


class Register(AbstractUser):
    name = models.CharField(max_length=50,default='')
    email = models.CharField(max_length=50,default='')
    contact = models.IntegerField(null=True)
    houseno = models.CharField(max_length=50,default='')
    street = models.CharField(max_length=50,default='')
    description = models.TextField(default='')
    id_proof = models.FileField(null=True, upload_to='id_proof/')
    gender = models.CharField(max_length=50,default='',choices=gender)
    qualification = models.CharField(max_length=50,default='')
    yearofexperience = models.CharField(max_length=50,default='')
    district = models.CharField(max_length=50,default='',choices=district)
    state = models.CharField(max_length=50,default='',choices=state)
    rank = models.CharField(max_length=50,default='')
    usertype=models.IntegerField(null=True,default=1)
    pin=models.IntegerField(null=True)

    status=models.IntegerField(null=True,default=1)

    
    
class chat(models.Model):
    senderid = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='sid')
    recieverid = models.ForeignKey(Register,on_delete=models.CASCADE,null=True,related_name='rid')
    messsage = models.FileField(max_length=50,default='')
    
# class DHORegister(models.Model):
#     DHOname = models.CharField(max_length=50,default='')
#     email = models.CharField(max_length=50,default='')
#     gender = models.CharField(max_length=50,default='')
#     qualification = models.CharField(max_length=50,default='')
#     yearofexperience = models.CharField(max_length=50,default='')
#     contact = models.IntegerField(null=True)
#     district = models.CharField(max_length=50,default='')
#     state = models.CharField(max_length=50,default='')
#     id_proof = models.FileField(null=True, upload_to='id_proof/')
    



   
   

empower_her_rise/authentication/forms.py
from django import forms
from . models import *
from Admin_App.models import *


class userregisterForm(forms.ModelForm):
    class Meta:
        model = Register
        fields = ['username','email','password','contact','district','pin','street','houseno']
        
        widgets = {
            "username" : forms.TextInput(attrs={'class':'style-input'}),
            "email" : forms.EmailInput(attrs={'class':'style-input'}),
            "contact" : forms.TextInput(attrs={'class':'style-input','maxlength':'10'}),
            "password" : forms.PasswordInput(attrs={'class':'style-input','maxlength':'10'}),
            "district" : forms.Select(attrs={'class':'style-input'}),
            "pin" : forms.TextInput(attrs={'class':'style-input'}),
            "street" : forms.TextInput(attrs={'class':'style-input'}),
            "houseno" : forms.TextInput(attrs={'class':'style-input'}),
            }
        help_texts = {
            'username' : None,
            'email' : '',
            'contact' : '',
            'password' : '',
        } 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['email'].required = False
        self.fields['contact'].required = False
        self.fields['password'].required = False                               
                      
        
class LoginForm(forms.ModelForm):
        
    class Meta:
        model = Register
        fields = ['username','password']
        
        widgets = {
            "username" : forms.TextInput(attrs={'class':'style-input'}),
            "password" : forms.PasswordInput(attrs={'class':'style-input','maxlength':'10'}),
            }  
        help_texts = {
            'username' : None,
           
            'password':''
        }
        
class orgregisterForm(forms.ModelForm):
        
    class Meta:
        model = Register
        fields = ['username','email','password','contact','description','id_proof']
        widgets = {
            "username" : forms.TextInput(attrs={'class':'style-input'}),
            "email" : forms.EmailInput(attrs={'class':'style-input'}),
            "contact" : forms.TextInput(attrs={'class':'style-input','maxlength':'10'}),
            "password" : forms.PasswordInput(attrs={'class':'style-input','maxlength':'10'}),
            "description" : forms.TextInput(attrs={'class':'style-input'}),
            "id_proof" : forms.FileInput(attrs={'class':'style-input'}),
             }
        help_texts = {
            'username' : None,
            'email' : '',
            'contact' : '',
            'password' : '',
        } 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['email'].required = False
        self.fields['contact'].required = False
        self.fields['password'].required = False                               
        
class DHOregisterForm(forms.ModelForm):
        
    class Meta:
        model = Register
        fields = ['username','gender','email','contact','password','qualification','yearofexperience','id_proof','district','state']
        
        widgets = {
            "username" : forms.TextInput(attrs={'class':'style-input'}),
            "gender" : forms.Select(attrs={'class':'style-input'}),
            "email" : forms.EmailInput(attrs={'class':'style-input'}),
            "contact" : forms.TextInput(attrs={'class':'style-input','maxlength':'10'}),
            "password" : forms.PasswordInput(attrs={'class':'style-input','maxlength':'10'}),

            "qualification" : forms.TextInput(attrs={'class':'style-input'}),
            "yearofexperience" : forms.TextInput(attrs={'class':'style-input'}),
            "id_proof" : forms.FileInput(attrs={'class':'style-input'}),
            "district" : forms.Select(attrs={'class':'style-input'}),
            "state" : forms.Select(attrs={'class':'style-input'}),
            }   
        help_texts = {
            'username' : None,
            'email' : '',
            'contact' : '',
            'password' : '',
        } 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['email'].required = False
        self.fields['contact'].required = False
        self.fields['password'].required = False                            
class policeofficerregisterForm(forms.ModelForm):
        
    class Meta:
        model = Register
        fields = ['username','contact','email','password','gender','rank','id_proof','district','state']
        
        widgets = {
            "username" : forms.TextInput(attrs={'class':'style-input'}),
            "contact" : forms.TextInput(attrs={'class':'style-input'}),
            "email" : forms.EmailInput(attrs={'class':'style-input'}),

            "password" : forms.PasswordInput(attrs={'class':'style-input','maxlength':'10'}),
            "gender" : forms.Select(attrs={'class':'style-input'}),
            "rank" : forms.TextInput(attrs={'class':'style-input'}),
            "district" : forms.Select(attrs={'class':'style-input'}),
            "state" : forms.Select(attrs={'class':'style-input'}),
            "id_proof" : forms.FileInput(attrs={'class':'style-input'}),
            }     
        help_texts = {
            'username' : None,
            'email' : '',
            'contact' : '',
            'password' : '',
        } 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['email'].required = False
        self.fields['contact'].required = False
        self.fields['password'].required = False       



class BookingForm(forms.Form):
    CardNumber = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'style-input'})
    )
    CVV = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'style-input'})
    )
    ExpiryDate = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'style-input'})
    )




 

empower_her_rise/authentication/templates/dhoreg.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DHO</title>
    <link rel="stylesheet" href="css/style-starter.css">
</head>
<body>
    <link href="css/style-starter.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{%static 'js/jquery-2.1.4.min.js' %}"></script>
    <div class="container">
        <h2>DHO</h2>
        <form action="#" method="post" enctype="multipart/form-data">
            <label for="org_name">DHO Name:</label>
            <input type="text" id="org_name" name="org_name" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <label for="contact">Contact:</label>
            <input type="tel" id="contact" name="contact" required>

            <label for="qualification">qualification:</label>
            <textarea id="qualification" name="qualification" rows="4" required></textarea>

            <label for="year of Experience">year of Experience:</label>
            <textarea id="year of Experience" name="year of Experience" rows="4" required></textarea>

            <label for="District">District:</label>
            <textarea id="District" name="District" rows="4" required></textarea>

            <label for="State">State:</label>
            <textarea id="State" name="State" rows="4" required></textarea>

            <label for="id_proof">ID Proof:</label>
            <input type="file" id="id_proof" name="id_proof" accept=".jpg, .jpeg, .png, .pdf" required>

            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>

empower_her_rise/authentication/templates/index.html
<!-- Author: W3layouts
Author URL: http://w3layouts.com -->

{%extends 'layout.html' %}
{% load static %}
{% block content %}


{% if messages %}
{% for message in messages %}
   <script>
    alert('{{message}}')
   </script>
{% endfor %}
{% endif %}
<body>
   

    <!-- banner section -->
    <section class="w3l-banner pt-5">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 banner-left">
                    <h3 class="text-white mb-3 title">Embrace Yourself <br>
                        For <span class="type-js"><span class="text-js">EVERYDAY </span></span></h3>
                    
                    </p>
                   
                </div>
            </div>
        </div>
    </section>
    <!-- //banner section -->

    <!-- about section -->
  
    <!-- //about section -->

    <!-- what we do section -->
    
    <!-- //customers section -->

    <!-- gallery section -->
    
    <!-- //gallery section -->

    <!-- block icons section -->
   
    <!-- //con
        tent with bg -->

    <!-- news -->
  
    <!-- //news -->

   

    <!-- Js scripts -->
  
{% endblock %}

empower_her_rise/authentication/templates/login.html
{%extends 'layout.html'%}
{% load static %}
{% block content %}

<!-- mail -->
<div class="w3_agile_map">
    <iframe src="{%static 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d158858.47339848557!2d-0.24168083557398998!3d51.528558242090796!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a00baf21de75%3A0x52963a5addd52a99!2sLondon%2C+UK!5e0!3m2!1sen!2sin!4v1480393569591' %}" style="border:0"></iframe>
</div>
<div class="latest-albums">
    <div class="container">
        
        <div class="wthree_latest_albums_grids gallery">
            <div class="col-md-8 agile_mail_grid_left">
                <h1 class="mb-5 text-center">{{title}}</h1>
                <form  method="post"> 
                    {% csrf_token %}
                    {{form.as_p}} 
                           
                    <input type="submit" value="Submit Now" >
                </form>
            </div>
           
        </div>
    </div>
</div>
<!-- //mail -->


{% endblock %}

empower_her_rise/authentication/templates/officer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>police Officer Registeration</title>
    <link rel="stylesheet" href="css/style-starter.css">
</head>
<body>
    <h2>police Officer Registration</h2>
    <link href="css/style-starter.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{%static 'js/jquery-2.1.4.min.js' %}"></script>
    <div class="container">
    <form action="#" method="POST">
        <label for="officername">Officer Name</label>
        <input type="text" id="officername" name="officername" required><br><br>

        <label for="contact">Contact:</label>
        <input type="text" id="contact" name="contact" required><br><br>

        <label for="gender">Gender:</label>
        <select id="gender" name="gender">
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
        </select><br><br>

        <label for="rank">Rank:</label>
        <input type="text" id="rank" name="rank" required><br><br>

        <label for="district">District:</label>
        <input type="text" id="district" name="district" required><br><br>

        <label for="state">State:</label>
        <input type="text" id="state" name="state" required><br><br>

        <label for="id_proof">ID Proof:</label>
        <input type="text" id="id_proof" name="id_proof" required><br><br>

        <input type="submit" value="Submit">
    </form>
</body>
</html>

empower_her_rise/authentication/templates/org.html
{% load static %}


<!-- js -->

<!-- //js -->
<!-- font-awesome-icons
 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Organization Registration</title>
    <link rel="stylesheet" href="css/style-starter.css">
</head>
<body>
    <link href="css/style-starter.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{%static 'js/jquery-2.1.4.min.js' %}"></script>
    <div class="container">
        <h2>Organization Registration</h2>
        <form action="#" method="post">
            <label for="org_name">Organization Name:</label>
            <input type="text" id="org_name" name="org_name" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <label for="contact">Contact:</label>
            <input type="tel" id="contact" name="contact" required>

            <label for="description">Description:</label>
            <textarea id="description" name="description" rows="4" required></textarea>

            <label for="id_proof">ID Proof:</label>
            <input type="file" id="id_proof" name="id_proof" accept=".jpg, .jpeg, .png, .pdf" required>

            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>

empower_her_rise/authentication/templates/register.html
{% extends "layout.html" %}
{% block content  %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<!-- mail -->



<!-- //js -->
<!-- font-awesome-icons -->

<!-- <div class="latest-albums">
    <div class="container">
        <h3 class="agileits_w3layouts_head">Register <span>Here</span></h3>
        <p class="w3_agileits_para">Quisque faucibus vel leo a luctus.</p>
        <div class="wthree_latest_albums_grids gallery">
            <div class="col-md-8 agile_mail_grid_left">
                <form  method="post"> 
                   
                    <input type="submit" value="Submit Now" >
                </form>
            </div>
           
        </div>
    </div>
    
</div> -->

<style>
    body{
        /* background-image: url("{%static 'assets/images/womenem.jpg'  %}"); */
    }
    label{
        color: yellow;
    }
    form{
        background-color: rgba(255, 255, 255, 0.093);

    }
</style>

<div class="form-41-mian  pt-lg-6 pt-md-4 cover-div w3l-banner ">

    <div class="container mx-auto">

        <div class="form-inner-cont">
            <h1 class="mb-5 text-center text-white"><b><i> {{title}}</i>  </b></h1>

            <form method="post" class="signin-form" enctype="multipart/form-data">
               
                    {% csrf_token %}
                    {{form.as_p}}  
                
                <div class="submit text-left">
                    <button type="submit" class="btn btn-style-white btn-style-primary">Submit
                     </button>
                </div>
            </form>
        </div>
      
    </div>
</div>
{% if validation %}
<script>
$(document).ready(function(){

    $("button[type='submit']").on("click",function(){
   
     
     name=$("input[name='username']").val()
     email=$("input[type='email']").val()
     password=$("input[name='password']").val()
     phone=$("input[name='contact']").val()
     var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  
     if(name==""){
      alert("Enter name!!!!!!!!!!!!!!!!!!");
      return false;
     } 
     if(email=="" || !emailRegex.test(email)){
      alert("Enter Valid Email!!!!!!!!!!!!!!!!!!!1");
      return false;
     } 
   
     if(password==""){
      alert("Enter password!!!!!!!!!!!!!!!!!!");
      return false;
     } 
     if(phone ="" || phone.length!=10){ 
      alert("Enter valid phone number");
      return false;
     } 
   
     
  })
 })

 </script>
 
 {% endif %}
 <script>
    
 $("#id_class_type").on("change",function(){
    if($("#id_class_type").val() == "online"){
        $("label[for=id_place]").hide()
        $("#id_place").hide()
    }
    else if($("#id_class_type").val() == "offline"){
        $("label[for=id_place]").show()
        $("#id_place").show()
    }

 });
 </script>
 {% if request.session.ut == 2 %}
 <script>
  $("label[for=id_amount]").show()
    $("#id_amount").show()
 </script>
 {% else %}
 <script>
    $("label[for=id_amount]").hide()
    $("#id_amount").hide()

 </script>

 {% endif %}
 
 {% if payment %}
 <script>
    $(document).ready(function(){


        $("button[type=submit]").click(function(){
       

        var cardNumber = $("#id_CardNumber").val();
        var cardNumberPattern = /^[0-9]{16}$/; // Assuming a 16 digit card number
        if (!cardNumberPattern.test(cardNumber)) {
            alert("Invalid Card Number. It should be 16 digits.");
            return false
    
        }

        var cvv = $("#id_CVV").val();
        var cvvPattern = /^[0-9]{3,4}$/; // Assuming 3 or 4 digit CVV
        if (!cvvPattern.test(cvv)) {
            alert("Invalid CVV. It should be 3 or 4 digits.");
            return false;
        }

        var expiryDate =  $("#id_ExpiryDate").val();
        var expiryDatePattern = /^(0[1-9]|1[0-2])\/([0-9]{2})$/; // MM/YY format
        if (!expiryDatePattern.test(expiryDate)) {
            alert("Invalid Expiry Date. It should be in MM/YY format.");
            return false;
        }
        })

});
</script>
 {% endif %}
 {% if checkup %}
 <script>
        $(document).ready(function(){
            function validatedate(){
                current_data=new Date()
                slected_data=new Date($("#id_date").val())
                if (slected_data <= current_data) {
                    alert("Select Valid Date");
                    return false;
                    
                }
            }
         
            $("#id_date").change(function(){
                return validatedate();
            })
            $("button[type=submit]").click(function(){
               return validatedate();
            })
            

        })

 </script>

 {% endif %}



 {% if Time %}
 <script>
    $(document).ready(function(){
        function validateTime() {
            var start_time = $("#id_start_time").val();
            var end_time = $("#id_end_time").val();

            if (new Date(start_time) >= new Date(end_time)) {
                alert("Start time should be less than end time.");
                return false;
            }
            
        }
        $("#id_end_time").change(function(){
                return validateTime();
            })

        $("button[type=submit]").click(function(){
            return validateTime();
        })
            
    });
</script>
{% endif %}

{% endblock %}

empower_her_rise/authentication/templates/user.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>user</title>
    <link rel="stylesheet" href="css/style-starter.css">
</head>
<body>
    <link href="css/style-starter.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{%static 'js/jquery-2.1.4.min.js' %}"></script>
    <div class="container">
        <h2>user</h2>
        <form action="#" method="post">
            <label for="org_name">Name:</label>
            <input type="text" id="org_name" name="org_name" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <label for="contact">Contact:</label>
            <input type="tel" id="contact" name="contact" required>

            <label for="houseno">houseno:</label>
            <textarea id="houseno" name="houseno" rows="4" required></textarea>
            
            <label for="Street">Street</label>
            <textarea id="Street" name="Street" rows="4" required></textarea>

            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>